export type Role='solar'|'consumer'|'prosumer';
export type Meter={id:string;name:string;role:Role;generation:number;load:number;status:'surplus'|'deficit'};
export type Trade={id:string;buyer:string;seller:string;kwh:number;price:number;distance:number;lossPct:number;time:string};
export type Order={id:string;side:'bid'|'ask';owner:string;kwh:number;price:number};
export const PFIT=3, PGRID=7;
export const seedMeters:Meter[]=[['M-01','Asha Solar','solar',4.8,1.7],['M-02','Ravi Home','consumer',.3,3.4],['M-03','Meera House','prosumer',3.9,2],['M-04','Ananya Villa','solar',5.2,1.6],['M-05','Kabir Home','consumer',.2,2.7],['M-06','Ishita Flat','prosumer',2.8,2.1],['M-07','Nikhil Home','consumer',.1,2.4],['M-08','Tara Solar','solar',4.3,1.2],['M-09','Dev House','prosumer',3.1,2.5],['M-10','Saanvi Home','consumer',.2,2.9],['M-11','Arjun Solar','solar',3.7,1.4],['M-12','Zoya Home','consumer',.3,2.2]].map(([id,name,role,generation,load])=>({id,name,role,generation,load,status:generation>load?'surplus':'deficit'} as Meter));
export const baseTrades:Trade[]=[{id:'T-1042',buyer:'Ravi Home',seller:'Asha Solar',kwh:1.2,price:5.08,distance:180,lossPct:0.27,time:'now'},{id:'T-1041',buyer:'Kabir Home',seller:'Ananya Villa',kwh:.8,price:5.18,distance:240,lossPct:0.36,time:'2m ago'},{id:'T-1040',buyer:'Nikhil Home',seller:'Tara Solar',kwh:1.6,price:4.92,distance:310,lossPct:0.47,time:'4m ago'},{id:'T-1039',buyer:'Zoya Home',seller:'Meera House',kwh:.6,price:5.04,distance:120,lossPct:0.18,time:'7m ago'}];
export function lmpFor(supply:number,demand:number){return Math.max(PFIT,Math.min(PGRID,(supply*PFIT+demand*PGRID)/(supply+demand)))}
export function ordersFor(meters:Meter[],price:number):Order[]{const asks=meters.filter(m=>m.status==='surplus').map((m,i)=>({id:`A-${i}`,side:'ask' as const,owner:m.name,kwh:Number(Math.max(.1,m.generation-m.load).toFixed(1)),price:Number(Math.max(PFIT,price-.18-(i%3)*.06).toFixed(2))}));const bids=meters.filter(m=>m.status==='deficit').map((m,i)=>({id:`B-${i}`,side:'bid' as const,owner:m.name,kwh:Number(Math.max(.1,m.load-m.generation).toFixed(1)),price:Number(Math.min(PGRID,price+.16-(i%3)*.04).toFixed(2))}));return [...asks,...bids]}
export function matchOrders(orders:Order[],tick:number):Trade[]{const asks=orders.filter(o=>o.side==='ask'),bids=orders.filter(o=>o.side==='bid');if(!bids.length)return [];return asks.slice(0,4).map((ask,i)=>{const bid=bids[i%bids.length],distance=120+((i*73+tick*11)%230),lossPct=distance/1000*1.5;const deliveredAsk=ask.price*(1+lossPct/100);return {id:`T-${1042-i}`,buyer:bid.owner,seller:ask.owner,kwh:Number(Math.min(ask.kwh,bid.kwh).toFixed(1)),price:Number(((bid.price+deliveredAsk)/2).toFixed(2)),distance,lossPct:Number(lossPct.toFixed(2)),time:i===0?'now':`${i*2}m ago`}})}
